lib/axlsx/package.rb
test/drawing/tc_pic.rb

Previously content types were only added for jpg, png,.. (lowercase) extensions, now it also adds content types for JPG, PNG... (uppercase)

Fix content types for uppercased image file extensions

---

examples/example.rb

An example for changing the row height was missing. I thought it would make sense to have this in example as well. I needed the option and I have to look at the code to how to do it. I think it would help others.

Added an example of row height

---

examples/example.rb

I think that examples are one of the best places for documentation and I just wasted 30 minutes trying to debug why my styles were not taking effect.

Add usage information to row_column_style example

---

lib/axlsx/drawing/scatter_series.rb
test/drawing/tc_scatter_series.rb

I noticed I was getting line smoothing even when a scatter chart's scatter style was set to a non-smoothed one. This change should set the series smoothing defaults based on scatter style of the chart but also allows smoothing to be enabled or disabled on a per-series basis.
Unfortunately this seems to be Excel-specific behaviour and is technically in violation of the Office Open XML standard (see http://msdn.microsoft.com/en-us/library/ff535259(v=office.12).aspx) but since Excel isn't compliant with the standard, I don't see another way to do this and have it work in Excel.
I added tests for default smooth settings and overriding smooth settings.

Add support for enabling or disabling smoothed lines in a scatter series

---

examples/example.rb
lib/axlsx/workbook/worksheet/sheet_pr.rb

https://github.com/randym/axlsx/issues/366

Option to change tab color

---

lib/axlsx/drawing/pic.rb

I needed to access transparency on images for a project, here's my quick and dirty patch to make that accessible. I'm open to feedback on how to make this pull request better fit into your project.
0 = transparent  100000 = opaque
It might make sense to multiply the value by 10,000 and subtract from 100,000 to get to an alpha percentage value.

Make alpha option accessible for pictures 

---

lib/axlsx/workbook/worksheet/cell.rb
test/workbook/worksheet/tc_cell.rb

This patch is to fix incorrect output of a cell associated with an instance of `ActiveSupport::TimeWithZone`.
`TimeWithZone` has an instance method `to_time` and `Axlsx::Cell#cast_value` will call it. However, the returned value of `TimeWithZone#to_time` is an instance of `Time` and and it is without instance specific time zone. The output Excel file may contain incorrect local time.
If the value `is_a?(Time)`, usually it means the class is a subclass of `Time`, there should be no need to call `#to_time` explicitly.

Skip to_time if the value is a Time instance

---

lib/axlsx/drawing/str_val.rb
test/drawing/tc_str_val.rb

Hi. I'm using `2.1.0.pre` and noticed that my pie charts wouldn't render properly (OpenOffice 4.0.1, for what it's worth) if one of the category labels happened to have an "&" in it. I unzipped the file to verify that they were escaped in the spreadsheet XML but not in the chart XML. Here's a PR to escape special characters for chart string values that fixes the issue for me.

Escape special characters in chart `StrVal`

---

lib/axlsx/util/constants.rb

There's a typo in the declaration of the core properties relationship type.
See, for example, <https://msdn.microsoft.com/en-us/library/windows/desktop/dd742699.aspx>, for the correct definition.

Fix core rels namespace

---

README.md

This trivial change uses the shiny SVG build icon badge instead of the slightly-off PNG.
_Thanks for maintaining this project!_

README: Use SVG icon for Travis badge [ci skip]

---

Gemfile
appveyor.yml

Hi!
Issue #419 mentions Windows testing as a step towards a new release.
This PR adds setup for testing on AppVeyor.  The tests are running on my fork here:
https://ci.appveyor.com/project/donv/axlsx
This PR also includes adjusting the `Gemfile` to work with Ruby 1.9.x.
Slightly ironically, the tests succeed on Ruby 1.9.3 while there are only **two** failing tests for Ruby 2.0+.  I leave fixing the two failing tests for another committer 😄 .
After merging this PR, the build needs to be activated in AppVeyor.  I would be happy to do that, but I would need admin access to this repo to enable commit callback hooks.

Enable Windows testing on AppVeyor

---

.travis.yml

This PR changes to build against the stable release of JRuby.
I also changed the Travis build matrix to use  rvm/env pairs, to be able to say exactly what to use where.
- @randym Ruby 1.9.2. This version is no longer supported by the Trusty machine that Travis has. Do you still need to build for 1.9.2? Controversial or not, I removed it from the matrix in this PR.

Travis: Test on JRuby 9.1.5.0

---

lib/axlsx/workbook/worksheet/merged_cells.rb
test/tc_axlsx.rb
test/workbook/worksheet/tc_worksheet.rb

This PR updates `Worksheet.merge_cells` to allow a `Row` to be passed (or `row.cells`). Previously, it was necessary to call `sheet.merge_cells row.cells.to_a`.

Allow a Row to be passed to merge_cells

---

lib/axlsx/drawing/pic.rb
lib/axlsx/drawing/scaling.rb
lib/axlsx/drawing/view_3D.rb
lib/axlsx/util/simple_typed_list.rb
lib/axlsx/util/validators.rb
lib/axlsx/workbook/worksheet/worksheet.rb
test/stylesheet/tc_styles.rb
test/util/tc_simple_typed_list.rb
test/workbook/worksheet/tc_worksheet.rb

fix Fixnum deprecated warning on Ruby2.4-preview3.
Fixnum was unify into Integer.
https://bugs.ruby-lang.org/issues/12005

fix warning: constant ::Fixnum is deprecated

---

.travis.yml
Gemfile
README.md
appveyor.yml
lib/axlsx/workbook/worksheet/cell.rb
lib/axlsx/workbook/worksheet/cell_serializer.rb
lib/axlsx/workbook/worksheet/merged_cells.rb
lib/axlsx/workbook/worksheet/row.rb
test/tc_axlsx.rb
test/workbook/worksheet/tc_cell.rb
test/workbook/worksheet/tc_row.rb
test/workbook/worksheet/tc_worksheet.rb

Hi 
I think it's convenient if we can set color of row at once.
With this method, we can emphasize special row without knowing a bit complex style option.
Something like .... 
```
p.workbook.add_worksheet(:name => "Table") do |sheet|
people.each do |person|
row = sheet.add_row([person.name, person.age])
row.color="00FFFF00" if person.salary > 100_000_000
end
end
```

set color with Row#color=

---

lib/axlsx/workbook/worksheet/worksheet.rb
test/workbook/tc_workbook.rb

Previously, worksheet name was defined as a serializable_attributes that Axlsx automatically camelize by Axlsx.camel .
This cause an unexpected worksheet name convertion.
For instance,
- "Pie_chart" is converted into "Piechart"
- "_example" is converted into "Example"
This patch disables an unexpected worksheet name convertion.

Fix #472: worksheet name with underscore

---

lib/axlsx/stylesheet/num_fmt.rb
lib/axlsx/workbook/worksheet/pivot_table.rb
test/workbook/worksheet/tc_pivot_table.rb

Fixes issues in the pivot table class and one tiny fix to number formats to avoid removing underscores

Pivot table bugs

---

Gemfile
axlsx.gemspec

The latest `rubyzip` release has a fix to disable JRuby's ObjectSpace, along with other bug fixes. There doesn't appear to be any major breaking changes:
https://github.com/rubyzip/rubyzip/blob/master/Changelog.md#120
Addresses #468

Bump rubyzip to 1.2.0

---

axlsx.gemspec

According to [NIST CVE-2017-5946](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-5946), RubyZip versions less than 1.2.1 have a directory traversal vulnerability so I changed the gemspec to force RubyZip version 1.2.1 to prevent this vulnerability.

Fix RubyZip vulnerability [URGENT]

---

.travis.yml

This PR updates Travis to use latest stable of JRuby.

Travis: Use jruby-9.1.8.0

---

.travis.yml

Update Travis CI to use latest Rubies.
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/

CI against latest rubies

---

lib/axlsx/package.rb
test/tc_helper.rb
test/tc_package.rb

Need this patch to sort archive entries to match the file format generated by MS Excel.  Without it, files generated by `axlsx` would have `application/zip` mime type.
```
MimeMagic.by_magic(File.open('tmp/foo.xlsx')).type 
=> "application/zip"
```
```
MimeMagic.by_magic(File.open('tmp/ms.xlsx')).type
=> "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
```

Sort archive entries for correct MIME detection

---

lib/axlsx/workbook/worksheet/worksheet.rb

A small documentation fix adding a missing quote mark and curly bracket.

[ci skip] Fix the documentation for Worksheet#cols

---

lib/axlsx.rb
test/tc_axlsx.rb

Whenever a frozen string is passed as an input to any sanitized value, we are modifying it in place which raised a RuntimeError if that string is frozen (as you might expect constants like header or workbook names to be).  Use the safer delete() method which creates a new, modified copy of the string.

Axlsx.sanitize() uses delete() vs. delete!() for frozen strings
